services:
  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 